apiVersion: v1
kind: Pod
metadata:
  name: my-pod-with-init
spec:
  initContainers:
    - name: init-download
      image: busybox
      command:
        [
          "sh",
          "-c",
          "wget -O /usr/share/nginx/html/index.html https://raw.githubusercontent.com/harryheman/modern-html-starter-template/refs/heads/main/index.html",
        ]
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html-volume
      emptyDir: {}
